### ISSUE TITLE
South Australian subregion IDs are wrong in sub_regional_reference_nodes.csv

### ISSUE THREAD

**Issue by nick-gorman** [Open-ISP/ISPyPSA#6]
In sub_regional_reference_nodes.csv there are the lines:

South Australia,Central South Australia (SA),Torrens Island 66 kV
South Australia,South East South Australia (CESA),South East 132 kV

Indicating sub region IDs of SA in CESA, but in other tables in the work book and in the trace data the IDs CSA and SESA are used.

**Comment by prakaa** [comment]
Hmm, this is the data as it is in the workbook. We could patch in the "right" IDs in the same way that's been implemented for NEM regions:

1. Add a hard-coded mapping, like the region mapping here: https://github.com/Open-ISP/ISPyPSA/blob/81991cd84035bf1abe7e63ed036ffc58a0fab9e2/src/ispypsa/templater/mappings.py#L9

2. Fuzzy match IDs in the templater

**Comment by nick-gorman** [comment]
Maybe the hard coded mapping is best, the codes are so short I'd be worried the fuzzy mapping will be wrong on occasion.

I can implement this and put in a PR.

**Comment by prakaa** [comment]
I was actually suggesting this as a two-step process, not either/or. This is how it's currently implemented for regions. But take your point, may mismatch for sub-regions:

https://github.com/Open-ISP/ISPyPSA/blob/b091481188706960a7bd8338107907f273acc31e/src/ispypsa/templater/nodes.py#L175

**Comment by nick-gorman** [comment]
OK if the fuzzy matching is on the sub regional names rather than IDs there probably a lot less change of mismatching.

**Comment by nick-gorman** [comment]
OK if it was implemented like that, with the fuzzy matching on names rather than IDs there probably less chance of mismatching.
