### ISSUE TITLE
Mapping to sub_regions when regional granularity is specified

### ISSUE THREAD

**Issue by nick-gorman** [Open-ISP/ISPyPSA#7]
At the moment with the regional template, we map to just a single subregion, which makes sense. However, when building the demand traces, I think we'd need to sum across all of the subregional nodes in a region to get the total for the region, which begs the question if the node input file doesn't have this mapping where does the translator get it from? Maybe the templater needs to also spit out a separate mapping file that is always created specifying the full mapping between region, subregion, and rez?

**Comment by prakaa** [comment]
That makes sense. 

Agreed with your approach for a subregional node mapping. I reckon this looks like calling `_template_sub_regional_nodes` regardless of the specified granularity, and then dropping columns from it

The REZ mapping file is a separate table. That should be templated too though.

Should I implement or will you?

**Comment by nick-gorman** [comment]
I've gone with the approach of just adding the REZ mapping table as this also includes the region to sub region mapping, which can be extracted through a simple groupby.
